spring:
  application:
    name: service-edu
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.52.150.44:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Aa123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 106.52.150.44:8848

server:
  port: 8001

#maven默认只加载main/java下的java文件，其他文件不主动加载，所以需要配置，
#二种方法1.将xml文件夹复制到输出目录target下
#2.在application下进行如下配置并在maven文件中配置如下
#  <build>
#  <resources>
#  <resource>
#  <directory>src/main/java</directory>
#  <includes>
#  <include>**/*.xml</include>
#  </includes>
#  <filtering>false</filtering>
#  </resource>
#  </resources>
#  </build>
mybatis-plus:
  mapper-locations: classpath:/com/jm/eduservice/mapper/xml/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

